CREATE TABLE alunos (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    CPF VARCHAR(14) UNIQUE NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    DATA_CADASTRO DATE NOT NULL DEFAULT (CURRENT_DATE),
    STATUS ENUM('ATIVO', 'INATIVO') NOT NULL DEFAULT 'ATIVO' 
);