ALTER TABLE alunos ADD COLUMN ATIVO BOOLEAN;

UPDATE alunos 
SET ATIVO = CASE
    WHEN STATUS = 'ATIVO' THEN TRUE
    WHEN STATUS = 'INATIVO' THEN FALSE
    ELSE NULL
END;

ALTER TABLE alunos DROP COLUMN STATUS;
