CREATE TABLE professores (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255),
    CPF VARCHAR(14),
    EMAIL VARCHAR(255),
    TELEFONE VARCHAR(20),
    DATA_NASCIMENTO DATE,
    DATA_CADASTRO DATE,
    ATIVO BOOLEAN
);
