-- 1. Criar tabela disciplinas
CREATE TABLE disciplinas (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL
);

-- 2. Criar tabela turma
CREATE TABLE turma (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_PROFESSOR BIGINT,
    ID_DISCIPLINA BIGINT,
    CONSTRAINT FK_TURMA_PROFESSOR FOREIGN KEY (ID_PROFESSOR) REFERENCES professores(ID),
    CONSTRAINT FK_TURMA_DISCIPLINA FOREIGN KEY (ID_DISCIPLINA) REFERENCES disciplinas(ID)
);

-- 3. Criar tabela de associação entre turma e aluno
CREATE TABLE turma_aluno (
    ID_TURMA BIGINT NOT NULL,
    ID_ALUNO BIGINT NOT NULL,
    PRIMARY KEY (ID_TURMA, ID_ALUNO),
    CONSTRAINT FK_TURMA_ALUNO_TURMA FOREIGN KEY (ID_TURMA) REFERENCES turma(ID),
    CONSTRAINT FK_TURMA_ALUNO_ALUNO FOREIGN KEY (ID_ALUNO) REFERENCES alunos(ID)
);
